
# load required package
```{r}
library(data.table)
library(tidyverse)
library(survminer)
library(survival)
library(ggridges)
library(qvalue)
library(readxl)
library(verification)
library(pROC)
library(scales)
library(RColorBrewer)
library(stats)
library(caret)

```

# Set parameters and directories
```{r}
main_fig_dir = "../03.Results/"
cols = c("black", "#A6CEE3", "#1F78B4", "#B2DF8A", "#33A02C", "#FB9A99", "#E31A1C", "#FDBF6F", "#FF7F00", "#CAB2D6", "#6A3D9A") #brewer.pal(n = 11, name = "Paired")
show_col(cols)
cols2 = c("black", "#A6CEE3", "#1F78B4", "#33A02C", "#FB9A99", "#FDBF6F", "#FF7F00", "#CAB2D6", "#6A3D9A") #brewer.pal(n = 11, name = "Paired")
show_col(cols2)
```



# load data 
```{r}
LLRmodelNA = 'LLR6' #  'LLR6'  'LLR5noTMB'  'LLR5noChemo'

train_LLR6score_df = read_excel(paste0(result_dir,LLRmodelNA,'_Scaler(StandardScaler)_prediction.xlsx'), "0", col_names = TRUE)
train_RF6score_df = read_excel(paste0(result_dir,'RF6_Scaler(None)_prediction.xlsx'), "0", col_names = TRUE)

selected_cols = c("SAMPLE_ID", "CancerType", "Response")

train_info_df = read_excel(paste0(input_dir,'features_phenotype_allDatasets.xlsx'), "Chowell2015-2017")
train_info_df = train_info_df[selected_cols]

train_info_df = merge(x = train_info_df, y = train_LLR6score_df[c("SAMPLE_ID","y_pred")], by = "SAMPLE_ID")
train_info_df = merge(x = train_info_df, y = train_RF6score_df[c("SAMPLE_ID","y_pred")], by = "SAMPLE_ID")
colnames(train_info_df) = c(selected_cols, c("LLR6score","RF6score"))

CancerTypes = unique(train_info_df$CancerType)

```


# determine optimal LLR6score or RF6score percentile threshold by maximizing sensitivity + specificity
```{r}

performance_diffCutoff = data.frame()
for (quant_cutoff in seq(0.1, 0.9, by=0.1)){  # 0.001
  train_df_temp = train_info_df %>% group_by(CancerType) %>% mutate(
         score_01 = ifelse(LLR6score >= quantile(LLR6score, quant_cutoff), 1, 0),
         )
  # calculate confusion matrix
  confusion <- confusionMatrix(as.factor(train_df_temp$score_01), as.factor(train_df_temp$Response))
  # extract sensitivity and specificity
  sensitivity <- confusion$byClass["Sensitivity"]
  specificity <- confusion$byClass["Specificity"]
  sum_score = sensitivity + specificity
  performance_diffCutoff = rbind(performance_diffCutoff,data.frame(sum_score,quant_cutoff,'LLR6'))
}
colnames(performance_diffCutoff) = c('performance','threshold', 'Model')

performance_diffCutoff2 = data.frame()
for (quant_cutoff in seq(0.1, 0.9, by=0.1)){
  train_df_temp = train_info_df %>% group_by(CancerType) %>% mutate(
         score_01 = ifelse(RF6score >= quantile(RF6score, quant_cutoff), 1, 0),
         )
  # calculate confusion matrix
  confusion <- confusionMatrix(as.factor(train_df_temp$score_01), as.factor(train_df_temp$Response))
  # extract sensitivity and specificity
  sensitivity <- confusion$byClass["Sensitivity"]
  specificity <- confusion$byClass["Specificity"]
  sum_score = sensitivity + specificity
  performance_diffCutoff2 = rbind(performance_diffCutoff2,data.frame(sum_score,quant_cutoff,'RF6'))
}
colnames(performance_diffCutoff2) = c('performance','threshold', 'Model')

performance_diffCutoff = rbind(performance_diffCutoff,performance_diffCutoff2)

performance_diffCutoff$threshold = performance_diffCutoff$threshold * 100

pdf(paste(main_fig_dir,paste0("FigureS5AA_optimal_PercentileCutoff_",LLRmodelNA,"_RF6.pdf"),sep = ""),width=3, height=2.5)
ggplot(performance_diffCutoff, aes(x = threshold, y = performance, color = Model, fill = Model)) + 
  geom_line(size=1) +
  theme_bw()+
  theme(legend.position= c(.8, .95),, #"none", c(0.8, 0.2)
        panel.border = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        # Change axis line
        axis.line = element_line(colour = "black"),
        axis.text.x = element_text(color="black"),
        axis.text.y = element_text(color="black"),
        axis.ticks = element_line(color = "black")) + 
  labs(x = "Threshold (%)", y = "Sensitivity + specificity") + # Threshold (percentile)
  scale_x_continuous(limits = c(0, 100)) + # 100
  scale_y_continuous(limits = c(0.5, 1.8))

dev.off()


```


# determine optimal LLR6score or RF6score absolute threshold by maximizing sensitivity + specificity
```{r}

performance_diffCutoff = data.frame()
for (cutoff in seq(0.01, 0.99, by=0.01)){  # 0.001
  train_df_temp = train_info_df %>% group_by(CancerType) %>% mutate(
         score_01 = ifelse(LLR6score >= cutoff, 1, 0),
         )
  # calculate confusion matrix
  confusion <- confusionMatrix(as.factor(train_df_temp$score_01), as.factor(train_df_temp$Response))
  # extract sensitivity and specificity
  sensitivity <- confusion$byClass["Sensitivity"]
  specificity <- confusion$byClass["Specificity"]
  sum_score = sensitivity + specificity
  performance_diffCutoff = rbind(performance_diffCutoff,data.frame(sum_score,cutoff,'LLR6'))
}
colnames(performance_diffCutoff) = c('performance','threshold', 'Model')

performance_diffCutoff2 = data.frame()
for (cutoff in seq(0.01, 0.99, by=0.01)){
  train_df_temp = train_info_df %>% group_by(CancerType) %>% mutate(
         score_01 = ifelse(RF6score >= cutoff, 1, 0),
         )
  # calculate confusion matrix
  confusion <- confusionMatrix(as.factor(train_df_temp$score_01), as.factor(train_df_temp$Response))
  # extract sensitivity and specificity
  sensitivity <- confusion$byClass["Sensitivity"]
  specificity <- confusion$byClass["Specificity"]
  sum_score = sensitivity + specificity
  performance_diffCutoff2 = rbind(performance_diffCutoff2,data.frame(sum_score,cutoff,'RF6'))
}
colnames(performance_diffCutoff2) = c('performance','threshold', 'Model')

performance_diffCutoff = rbind(performance_diffCutoff,performance_diffCutoff2)

performance_diffCutoff$threshold = performance_diffCutoff$threshold

pdf(paste(main_fig_dir,paste0("FigureS5AA_optimal_AbsoluteCutoff_",LLRmodelNA,"_RF6.pdf"),sep = ""),width=3, height=2.5)
ggplot(performance_diffCutoff, aes(x = threshold, y = performance, color = Model, fill = Model)) + 
  geom_line(size=1) +
  theme_bw()+
  theme(legend.position= c(.8, .95),, #"none", c(0.8, 0.2)
        panel.border = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        # Change axis line
        axis.line = element_line(colour = "black"),
        axis.text.x = element_text(color="black"),
        axis.text.y = element_text(color="black"),
        axis.ticks = element_line(color = "black")) + 
  labs(x = "Threshold", y = "Sensitivity + specificity") + # Threshold (percentile)
  scale_x_continuous(limits = c(0, 1)) + # 100
  scale_y_continuous(limits = c(0.5, 1.8))

dev.off()


```
