
# load required package
```{r}
library(data.table)
library(tidyverse)
library(survminer)
library(survival)
library(ggridges)
library(qvalue)
library(readxl)
library(verification)
library(pROC)
```

# set the color scale
```{r}
my.cols <- c("#7CD5C8FF", "#507D41FF", "#DF8F44FF", "#6A6599FF", "#CB7C77FF", "#6B42C8FF",
             "#C9D73DFF", "#C555CBFF", "#AED688FF", "#502E71FF", "#C49A3FFF",
             "#42B540FF", "#0099B4FF", "#925E9FFF", 
             "#FDAF91FF", "#AD002AFF", "#00468BFF", "#ED0000FF",
             "#6A7DC9FF", "#D7652DFF", 
             "#CF4C8BFF", "#5D8D9CFF", "#722E41FF", "#C8B693FF", "#C5383CFF", "#79AF97FF", "#68D359FF")
```

# Set parameters and directories
```{r}
input_dir = "../02.Input/"
result_dir = "../03.Results/"

LLRmodelNA = 'LLR6' # 'LLR6'  'LLR5noTMB'   'LLR5noChemo'

if (LLRmodelNA=='LLR6'){
  absoluteCutoff = 0.44
}else if (LLRmodelNA=='LLR5noTMB'){
  absoluteCutoff = 0.48
}else if (LLRmodelNA=='LLR5noChemo'){
  absoluteCutoff = 0.43
}


```

# load data 
```{r}

test1_LLR6score_df = read_excel(paste0(result_dir,'NSCLC_',LLRmodelNA,'_Scaler(StandardScaler)_prediction.xlsx'), "1", col_names = TRUE)
test2_LLR6score_df = read_excel(paste0(result_dir,'NSCLC_',LLRmodelNA,'_Scaler(StandardScaler)_prediction.xlsx'), "2")
test3_LLR6score_df = read_excel(paste0(result_dir,'NSCLC_',LLRmodelNA,'_Scaler(StandardScaler)_prediction.xlsx'), "3")
LLR6score_df = rbind(test1_LLR6score_df,test2_LLR6score_df,test3_LLR6score_df)

selected_cols = c("SAMPLE_ID","TMB","PDL1_TPS(%)","Chemo_before_IO","Age","Drug","Sex","PFS_Event","PFS_Months","OS_Event","OS_Months")

test1_info_df = read_excel(paste0(input_dir,'features_phenotype_allDatasets.xlsx'), "Morris_new")
test1_info_df = test1_info_df[selected_cols]
test2_info_df = read_excel(paste0(input_dir,'features_phenotype_allDatasets.xlsx'), "Awad_NSCLC1")
test2_info_df = test2_info_df[selected_cols]
test3_info_df = read_excel(paste0(input_dir,'features_phenotype_allDatasets.xlsx'), "Awad_NSCLC2")
test3_info_df = test3_info_df[selected_cols]
test4_info_df = read_excel(paste0(input_dir,'features_phenotype_allDatasets.xlsx'), "Awad_NSCLC3")
test4_info_df = test4_info_df[selected_cols]
test5_info_df = read_excel(paste0(input_dir,'features_phenotype_allDatasets.xlsx'), "Lee_NSCLC")
test5_info_df = test5_info_df[selected_cols]

info_df = rbind(test1_info_df,test2_info_df,test3_info_df,test4_info_df,test5_info_df)
info_df = merge(x = info_df, y = LLR6score_df[c("SAMPLE_ID","y_pred")], by = "SAMPLE_ID")
colnames(info_df) = c(selected_cols, c("LLR6score"))

```


# K-M OS/PFS curves of LLR6scorehigh-TMBhigh VS LLR6scorehigh-TMBlow VS...
```{r}
TMB_cutoff = 10 # 15 10
info_df = info_df %>% mutate(
         LLR6score_01 = ifelse(LLR6score >= absoluteCutoff, "high", "low"),
         TMB_01 = ifelse(TMB >= TMB_cutoff, "high", "low"),
         )

quantile_plot <- info_df %>%
      mutate(LLR6_TMB_group = paste0(LLR6score_01, " LLR6score, ", TMB_01, " TMB"))

pdf(paste0(result_dir,"NSCLC_",LLRmodelNA,"_TMB_OS_curve.pdf"), width = 5*0.8, height = 3.9*0.8, onefile = F)
ggsurvplot(survfit(Surv(OS_Months, OS_Event) ~ LLR6_TMB_group, data = quantile_plot), pval = F, risk.table = F,
           palette = c("#9B2226","#001219", "#CA6702", "#005F73"),
           risk.table.height = 0.3, xlab = 'Time (months)', ylab = 'OS probability',
           legend = c(0.35, 1.1),
           legend.text = element_text(size = 7, color = "black"),
           legend.labs = c("LORIS-H/TMB-H", "LORIS-H/TMB-L", "LORIS-L/TMB-H", "LORIS-L/TMB-L"),
           ggtheme = theme(legend.background = element_rect(fill = NA, color=NA),legend.key = element_rect(fill = NA, color=NA),
                           plot.margin = unit(c(1.5, 0.2, 0.2, 0.2),"cm"),
                           panel.background = element_rect(fill = NA),
                           panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
                           panel.border = element_blank(),axis.line = element_line(colour = "black"),
                           axis.text.x = element_text(colour="black"),axis.text.y = element_text(colour="black")),  # top, right, bot, left
          pval.method = T, tables.y.text = F) +
  guides(color=guide_legend(ncol =1)) +
  labs(color = "")# +
  #theme(legend.position = c(0.4, 0.6))
dev.off()

##### HR and p-value comparison
cancerData=data.frame(info_df$LLR6score_01,info_df$OS_Months,info_df$OS_Event)
colnames(cancerData) = c("Score", "OS_Months", "OS_Event")
sfit = survfit(Surv(OS_Months,OS_Event) ~ Score, data=cancerData)
scox = coxph(Surv(OS_Months,OS_Event) ~ Score, data=cancerData)
scox_coef = summary(scox)$coefficients
HR_value = scox_coef[2] # hazard ratio
Z_value=scox_coef[4]
P_value=scox_coef[5]
HR_CI = exp(confint(scox))
print(paste(c('LLR6 OS: ', P_value,HR_value), collapse= " "))

cancerData=data.frame(info_df$TMB_01,info_df$OS_Months,info_df$OS_Event)
colnames(cancerData) = c("Score", "OS_Months", "OS_Event")
sfit = survfit(Surv(OS_Months,OS_Event) ~ Score, data=cancerData)
scox = coxph(Surv(OS_Months,OS_Event) ~ Score, data=cancerData)
scox_coef = summary(scox)$coefficients
HR_value = scox_coef[2] # hazard ratio
Z_value=scox_coef[4]
P_value=scox_coef[5]
HR_CI = exp(confint(scox))
print(paste(c('TMB OS: ', P_value,HR_value), collapse= " "))

##### p values between 4 different groups
quantile_plot_temp = quantile_plot[quantile_plot$LLR6_TMB_group=='high LLR6score, high TMB' | quantile_plot$LLR6_TMB_group=='low LLR6score, high TMB', ]
scox = coxph(Surv(quantile_plot_temp$OS_Months,quantile_plot_temp$OS_Event)~LLR6_TMB_group, data=quantile_plot_temp)
scox_coef = summary(scox)$coefficients
HR_value = scox_coef[2] # hazard ratio
Z_value=scox_coef[4]
P_value=scox_coef[5]
print(paste(c('p HR: ', P_value,HR_value), collapse= " "))
```



# K-M OS/PFS curves of LLR6scorehigh-PDL1high VS LLR6scorehigh-PDL1low VS...
```{r}
PDL1_cutoff = 50 # 5 50

info_df = info_df %>% mutate(
         LLR6score_01 = ifelse(LLR6score >= absoluteCutoff, "high", "low"),
         PDL1_01 = ifelse(`PDL1_TPS(%)` >= PDL1_cutoff, "high", "low"),
         )

quantile_plot <- info_df %>%
      mutate(LLR6_PDL1_group = paste0(LLR6score_01, " LLR6score, ", PDL1_01, " PDL1"))

pdf(paste0(result_dir,"NSCLC_",LLRmodelNA,"_PDL1_OS_curve.pdf"), width = 5*0.8, height = 3.9*0.8, onefile = F)
ggsurvplot(survfit(Surv(OS_Months, OS_Event) ~ LLR6_PDL1_group, data = quantile_plot), pval = F, risk.table = F,
           palette = c("#9B2226","#001219", "#CA6702", "#005F73"),
           risk.table.height = 0.3, xlab = 'Time (months)', ylab = 'OS probability',
           legend = c(0.35, 1.1),
           legend.text = element_text(size = 7, color = "black"),
           legend.labs = c("LORIS-H/PDL1-H", "LORIS-H/PDL1-L", "LORIS-L/PDL1-H", "LORIS-L/PDL1-L"),
           ggtheme = theme(legend.background = element_rect(fill = NA, color=NA),legend.key = element_rect(fill = NA, color=NA),
                           plot.margin = unit(c(1.5, 0.2, 0.2, 0.2),"cm"),
                           panel.background = element_rect(fill = NA),
                           panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
                           panel.border = element_blank(),axis.line = element_line(colour = "black"),
                           axis.text.x = element_text(colour="black"),axis.text.y = element_text(colour="black")),  # top, right, bot, left
          pval.method = T, tables.y.text = F) +
  guides(color=guide_legend(ncol =1)) +
  labs(color = "")# +
  #theme(legend.position = c(0.4, 0.6))
dev.off()

##### HR and p-value comparison
cancerData=data.frame(info_df$LLR6score_01,info_df$OS_Months,info_df$OS_Event)
colnames(cancerData) = c("Score", "OS_Months", "OS_Event")
sfit = survfit(Surv(OS_Months,OS_Event) ~ Score, data=cancerData)
scox = coxph(Surv(OS_Months,OS_Event) ~ Score, data=cancerData)
scox_coef = summary(scox)$coefficients
HR_value = scox_coef[2] # hazard ratio
Z_value=scox_coef[4]
P_value=scox_coef[5]
HR_CI = exp(confint(scox))
print(paste(c('LLR6 OS: ', P_value,HR_value), collapse= " "))

cancerData=data.frame(info_df$PDL1_01,info_df$OS_Months,info_df$OS_Event)
colnames(cancerData) = c("Score", "OS_Months", "OS_Event")
sfit = survfit(Surv(OS_Months,OS_Event) ~ Score, data=cancerData)
scox = coxph(Surv(OS_Months,OS_Event) ~ Score, data=cancerData)
scox_coef = summary(scox)$coefficients
HR_value = scox_coef[2] # hazard ratio
Z_value=scox_coef[4]
P_value=scox_coef[5]
HR_CI = exp(confint(scox))
print(paste(c('PDL1 OS: ', P_value,HR_value), collapse= " "))

##### p values between 4 different groups
quantile_plot_temp = quantile_plot[quantile_plot$LLR6_PDL1_group=='high LLR6score, high PDL1' | quantile_plot$LLR6_PDL1_group=='high LLR6score, low PDL1', ]
scox = coxph(Surv(quantile_plot_temp$OS_Months,quantile_plot_temp$OS_Event)~LLR6_PDL1_group, data=quantile_plot_temp)
scox_coef = summary(scox)$coefficients
HR_value = scox_coef[2] # hazard ratio
Z_value=scox_coef[4]
P_value=scox_coef[5]
print(paste(c('p HR: ', P_value,HR_value), collapse= " "))

```


# Correlation between LR score and PDL1 and TMB
```{r}
data_plot = info_df %>% drop_na(TMB, LLR6score)
data_plot$logTMB <- log10(data_plot$TMB + 1)

ggscatter(data_plot, x = "logTMB", y = "LLR6score", 
          shape = 21, xlab = "log10(TMB+1)", ylab = "LORIS", add = "reg.line") + #legend.title = "Cancer type", legend = "right", fill = "CancerType",palette = cols, 
  stat_cor(method = "spearman")
ggsave(paste0(result_dir,"NSCLC_TMB_LORIS(",LLRmodelNA,")_Corr.pdf"), width = 5.5, height = 3)


data_plot = info_df %>% drop_na('PDL1_TPS(%)', LLR6score)

ggscatter(data_plot, x = "PDL1_TPS(%)", y = "LLR6score", 
          shape = 21, xlab = "PD-L1 TPS (%)", ylab = "LORIS", add = "reg.line") + #legend.title = "Cancer type", legend = "right", fill = "CancerType",palette = cols, 
  stat_cor(method = "spearman")
ggsave(paste0(result_dir,"NSCLC_PDL1_LORIS(",LLRmodelNA,")_Corr.pdf"), width = 5.5, height = 3)

```
