
# load required package
```{r}
library(data.table)
library(tidyverse)
library(survminer)
library(survival)
library(ggridges)
library(qvalue)
library(readxl)
library(verification)
library(pROC)
```

# set the color scale
```{r}
my.cols <- c("#7CD5C8FF", "#507D41FF", "#DF8F44FF", "#6A6599FF", "#CB7C77FF", "#6B42C8FF",
             "#C9D73DFF", "#C555CBFF", "#AED688FF", "#502E71FF", "#C49A3FFF",
             "#42B540FF", "#0099B4FF", "#925E9FFF", 
             "#FDAF91FF", "#AD002AFF", "#00468BFF", "#ED0000FF",
             "#6A7DC9FF", "#D7652DFF", 
             "#CF4C8BFF", "#5D8D9CFF", "#722E41FF", "#C8B693FF", "#C5383CFF", "#79AF97FF", "#68D359FF")
```

# Set parameters and directories
```{r}
input_dir = "../02.Input/"
result_dir = "../03.Results/"
cutoff = 0.5

```

# load data (LLRx)
```{r}

dataType = 'NSCLC' # 'PanCancer'  'NSCLC'
LLRmodelNA = 'LLR6' #  'LLR6'  'LLR5noTMB'   'LLR5noChemo'  'TMB'
scalerType = 'StandardScaler'
if (LLRmodelNA == 'TMB'){
  scalerType = 'None'
}

test1_LLR6score_df = read_excel(paste0(result_dir,dataType,'_',LLRmodelNA,'_Scaler(',scalerType,')_prediction.xlsx'), "1", col_names = TRUE)
test2_LLR6score_df = read_excel(paste0(result_dir,dataType,'_',LLRmodelNA,'_Scaler(',scalerType,')_prediction.xlsx'), "2")
if (dataType == 'NSCLC'){
  test3_LLR6score_df = read_excel(paste0(result_dir,dataType,'_',LLRmodelNA,'_Scaler(',scalerType,')_prediction.xlsx'), "3")
  LLR6score_df = rbind(test1_LLR6score_df,test2_LLR6score_df, test3_LLR6score_df)
}else{
  LLR6score_df = rbind(test1_LLR6score_df,test2_LLR6score_df)
}

selected_cols = c("SAMPLE_ID","TMB","Chemo_before_IO","CancerType","Age","Drug","Sex","PFS_Event","PFS_Months","OS_Event","OS_Months")

if (dataType == 'NSCLC'){
  test1_info_df = read_excel(paste0(input_dir,'features_phenotype_allDatasets.xlsx'), "Morris_new")
  test1_info_df = test1_info_df[selected_cols]
  test1_info_df = test1_info_df[test1_info_df$CancerType=='NSCLC',]
  test2_1_info_df = read_excel(paste0(input_dir,'features_phenotype_allDatasets.xlsx'), "Awad_NSCLC1")
  test2_2_info_df = read_excel(paste0(input_dir,'features_phenotype_allDatasets.xlsx'), "Awad_NSCLC2")
  test2_3_info_df = read_excel(paste0(input_dir,'features_phenotype_allDatasets.xlsx'), "Awad_NSCLC3")
  test2_info_df = rbind(test2_1_info_df,test2_2_info_df,test2_3_info_df)
  test2_info_df = test2_info_df[selected_cols]
  test3_info_df = read_excel(paste0(input_dir,'features_phenotype_allDatasets.xlsx'), "Lee_NSCLC")
  test3_info_df = test3_info_df[selected_cols]
  info_df = rbind(test1_info_df,test2_info_df,test3_info_df)
  info_df = merge(x = info_df, y = LLR6score_df[c("SAMPLE_ID","y_pred")], by = "SAMPLE_ID")

}else{
  test1_info_df = read_excel(paste0(input_dir,'features_phenotype_allDatasets.xlsx'), "Chowell2018")
  test1_info_df = test1_info_df[selected_cols]
  test2_info_df = read_excel(paste0(input_dir,'features_phenotype_allDatasets.xlsx'), "Morris_new")
  test2_info_df = test2_info_df[selected_cols]
  info_df = rbind(test1_info_df,test2_info_df)
  info_df = merge(x = info_df, y = LLR6score_df[c("SAMPLE_ID","y_pred")], by = "SAMPLE_ID")
}

colnames(info_df) = c(selected_cols, c("LLR6score"))

```

# K-M OS/PFS curves of LLR6score
```{r}
quantile_plot = info_df %>% group_by(CancerType) %>%
  mutate(LLR6score_perct = ntile(LLR6score, n = n()) / n()) # ntile(LLR6score, length(breaks)-1, breaks=breaks)

quantile_plot = quantile_plot %>% 
  mutate(LLR6score_01 = ifelse(LLR6score_perct > 0.9, 6, ifelse(LLR6score_perct > 0.8, 5, ifelse(LLR6score_perct > 0.5, 4, ifelse(LLR6score_perct > 0.2, 3, ifelse(LLR6score_perct > 0.1, 2, ifelse(LLR6score_perct >= 0, 1, 0))))))) # ntile(LLR6score, length(breaks)-1, breaks=breaks)

pdf(paste0(result_dir,dataType,'_',LLRmodelNA,"_OS_curves.pdf"), width = 6.5*2.3/3, height = 4.5*2.3/3, onefile = F)
p <- ggsurvplot(survfit(Surv(OS_Months, OS_Event) ~ LLR6score_01, data = quantile_plot), palette = my.cols,
           risk.table = F, tables.y.text = F, risk.table.height = 0.3, #risk.table.margin =1,
           xlab = 'Time (months)', ylab = 'OS probability',
           legend = c(0.7, 0.98),
           legend.labs = c("0-10%", "10-20%", "20-50%", "50-80%", "80-90%", "90-100%"),
           pval = F, pval.method = T) +
  guides(color=guide_legend(ncol =1)) +
  labs(color = "") 

p$plot + theme(plot.margin = unit(c(3.15, 1, 1, 1), "lines")) # top, right, bottom, and left 
dev.off()

##### p values between 5 different groups
quantile_plot_temp = quantile_plot[quantile_plot$LLR6score_01==6 | quantile_plot$LLR6score_01==1, ]

quantile_plot_temp = quantile_plot_temp %>% mutate(
         LLR6score_01 = ifelse(LLR6score_01 == 6, "high", "low"),
         )
quantile_plot_temp$LLR6score_01 <- relevel(factor(quantile_plot_temp$LLR6score_01), ref = "high")

scox = coxph(Surv(quantile_plot_temp$OS_Months,quantile_plot_temp$OS_Event)~LLR6score_01, data=quantile_plot_temp)
scox_coef = summary(scox)$coefficients
HR_value = scox_coef[2] # hazard ratio
Z_value=scox_coef[4]
#P_value=scox_coef[5]
P_value= pnorm(Z_value, lower.tail = FALSE) # to test if higher score has better survival
print(paste0('HR_value: ', round(HR_value,2), '.  P_value: ', P_value))
```

